### ISSUE TITLE
Add documentation on replatforming and porting data

### ISSUE THREAD

**Issue by mridang** [Nosto/docs-nosto-com#41]

**Comment by StanislavKraus** [comment]
1) I want to understand which migrations are possible and which ones aren't, e.g. is it possible to migrate from M1/M2/Shopware/Prestashop to Shopify? Is it possible to migrate from Shopware to M2?  Is is possible to move from M1 to a custom platform?
In the end of the day, a table with possible/impossible migrations will be helpful.
2) I want to know which data has to stay the same so that I can migrate the most data from one platform to another. So far, I only know that the product ID has to stay the same. What else is recommended to stay they same to lose the least amount of data?

**Comment by mridang** [comment]
@StanislavKraus where should this article live? Would you like a section under each of the platform wikis?

**Comment by mridang** [comment]
@StanislavKraus I'm closing this for now. There's an M1 to M2 replatforming guide. If you get specific one for any platform, do let me know. https://github.com/Nosto/nosto-magento2/wiki/Migrating-to-Magento2
